// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in user calling this MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's projects, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of projects to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("projects").select("id, name, code, description, sort_order, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-workstations.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_workstations_default = defineTool3({
  name: "list_workstations",
  title: "List workstations",
  description: "List workstations for a given project belonging to the signed-in user.",
  inputSchema: {
    project_id: z2.string().uuid().describe("Project UUID to list workstations for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("workstations").select("id, project_id, name, code, design_responsible, sort_order, created_at, updated_at").eq("project_id", project_id).order("sort_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { workstations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-modules.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_modules_default = defineTool4({
  name: "list_modules",
  title: "List function modules",
  description: "List function modules for a given workstation belonging to the signed-in user.",
  inputSchema: {
    workstation_id: z3.string().uuid().describe("Workstation UUID to list modules for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workstation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("function_modules").select("id, workstation_id, name, code, sort_order, created_at, updated_at").eq("workstation_id", workstation_id).order("sort_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { modules: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yxjhungswhwahnbhahaq";
var mcp_default = defineMcp({
  name: "vision-workstation-mcp",
  title: "Vision Workstation MCP",
  version: "0.1.0",
  instructions: "Read the signed-in user's vision-workstation data. Use `whoami` to verify connectivity, `list_projects` to enumerate projects, `list_workstations` for a given project, and `list_modules` for a given workstation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_projects_default, list_workstations_default, list_modules_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
